repositories {
    google()
    mavenCentral()   // обязательно
}

plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

android {
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/INDEX.LIST']
        }
    }
    
}
kotlin {
    jvmToolchain(17)
}
kotlinOptions {
    jvmTarget = '17'
}

dependencies {
    // SSH (то, чего не хватает)
    implementation 'com.hierynomus:sshj:0.37.0'
    implementation 'org.bouncycastle:bcprov-jdk15to18:1.78.1'

    // Kotlin корутины (у тебя уже есть 1.6.4 — оставь одну строку, дубль убери)
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
}

